---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-app2
  namespace: default
  labels:
    app: nodejs-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app2
  template:
    metadata:
      labels:
        app: nodejs-app2
    spec:
      containers:
      - name: nodejs-app2
        image: "lijisha27/jenkis-k8s:latest2"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app2
  namespace: default
spec:
  selector:
    app:nodejs-app2
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 80
